export type CandidateStatus = "Recommended" | "Reviewing" | "Interview" | "Offer" | "Placed";
export type InternshipStatus = "Open" | "Interviewing" | "Filled" | "Draft";

export const employerProfile = {
  id: "regional-employer-001",
  companyName: "Lake Norman Industry Partner",
  contactName: "Morgan Ellis",
  role: "Talent Development Director",
  initials: "ME",
  industry: "Advanced Manufacturing",
  location: "Lake Norman, NC",
  activeInternships: 3,
  studentsInPipeline: 18,
  interviewsScheduled: 5,
  placements: 4,
};

export const employerNavigation = [
  { label: "Dashboard", href: "/employer/dashboard" },
  { label: "Candidates", href: "/employer/candidates" },
  { label: "Internships", href: "/employer/internships" },
  { label: "Analytics", href: "/employer/analytics" },
  { label: "Profile", href: "/employer/profile" },
];

export const employerCandidates = [
  {
    id: "ambassador-student-001",
    name: "Avery Thompson",
    school: "Ambassador Christian School",
    graduationYear: 2026,
    readinessScore: 82,
    portfolioProgress: 78,
    status: "Recommended" as CandidateStatus,
    availability: "Fall 2026",
    location: "Huntersville, NC",
    careerInterests: ["Business", "Sports Management", "Community Leadership"],
    topSkills: ["Communication", "Leadership", "Teamwork"],
    badges: ["Confident Communicator", "Future Vision", "Self-Awareness"],
    summary: "Emerging leader with strong communication, teamwork, and relationship-building strengths.",
  },
  {
    id: "ambassador-student-002",
    name: "Jordan Williams",
    school: "Ambassador Christian School",
    graduationYear: 2026,
    readinessScore: 76,
    portfolioProgress: 66,
    status: "Reviewing" as CandidateStatus,
    availability: "Fall 2026",
    location: "Davidson, NC",
    careerInterests: ["Technology", "Operations", "Business"],
    topSkills: ["Problem Solving", "Adaptability", "Communication"],
    badges: ["Career Explorer", "Professional Communicator"],
    summary: "Adaptable problem-solver interested in operations, technology, and business systems.",
  },
  {
    id: "ambassador-student-003",
    name: "Maya Brooks",
    school: "Ambassador Christian School",
    graduationYear: 2026,
    readinessScore: 79,
    portfolioProgress: 72,
    status: "Interview" as CandidateStatus,
    availability: "Spring 2027",
    location: "Cornelius, NC",
    careerInterests: ["Healthcare", "Human Resources", "Leadership"],
    topSkills: ["Teamwork", "Professionalism", "Leadership"],
    badges: ["Collaborative Teammate", "Professional Presence"],
    summary: "Professional, collaborative student with interest in people-focused leadership environments.",
  },
  {
    id: "ambassador-student-004",
    name: "Cameron Reed",
    school: "Ambassador Christian School",
    graduationYear: 2026,
    readinessScore: 68,
    portfolioProgress: 48,
    status: "Reviewing" as CandidateStatus,
    availability: "Fall 2026",
    location: "Mooresville, NC",
    careerInterests: ["Marketing", "Media", "Creative Services"],
    topSkills: ["Creativity", "Communication", "Adaptability"],
    badges: ["Story Builder", "Self-Awareness"],
    summary: "Creative communicator exploring marketing, media, and customer-facing career paths.",
  },
  {
    id: "ambassador-student-005",
    name: "Riley Carter",
    school: "Ambassador Christian School",
    graduationYear: 2026,
    readinessScore: 84,
    portfolioProgress: 81,
    status: "Offer" as CandidateStatus,
    availability: "Fall 2026",
    location: "Huntersville, NC",
    careerInterests: ["Project Management", "Business", "Community Impact"],
    topSkills: ["Leadership", "Teamwork", "Professionalism"],
    badges: ["Emerging Leader", "Future Vision", "Professional Communicator"],
    summary: "Reliable emerging leader with strong professionalism and project coordination potential.",
  },
  {
    id: "ambassador-student-006",
    name: "Noah Mitchell",
    school: "Ambassador Christian School",
    graduationYear: 2026,
    readinessScore: 71,
    portfolioProgress: 54,
    status: "Recommended" as CandidateStatus,
    availability: "Spring 2027",
    location: "Denver, NC",
    careerInterests: ["Engineering", "Skilled Trades", "Operations"],
    topSkills: ["Problem Solving", "Creativity", "Teamwork"],
    badges: ["Career Explorer", "Problem Solver"],
    summary: "Hands-on problem-solver interested in engineering, skilled trades, and operational environments.",
  },
];

export const internships = [
  {
    id: "internship-001",
    title: "Operations Internship",
    department: "Operations",
    location: "Huntersville, NC",
    schedule: "10–15 hours/week",
    term: "Fall 2026",
    status: "Open" as InternshipStatus,
    applicants: 8,
    interviews: 3,
    openings: 2,
    description: "Support process documentation, workflow improvement, and cross-functional project coordination.",
    requiredSkills: ["Communication", "Problem Solving", "Professionalism"],
  },
  {
    id: "internship-002",
    title: "Community Engagement Internship",
    department: "Community Relations",
    location: "Lake Norman, NC",
    schedule: "8–12 hours/week",
    term: "Fall 2026",
    status: "Interviewing" as InternshipStatus,
    applicants: 6,
    interviews: 2,
    openings: 1,
    description: "Assist with community partnerships, event logistics, outreach, and stakeholder communication.",
    requiredSkills: ["Communication", "Leadership", "Teamwork"],
  },
  {
    id: "internship-003",
    title: "Marketing Project Internship",
    department: "Marketing",
    location: "Hybrid",
    schedule: "8 hours/week",
    term: "Spring 2027",
    status: "Draft" as InternshipStatus,
    applicants: 0,
    interviews: 0,
    openings: 2,
    description: "Create content, support campaign planning, and organize digital marketing assets.",
    requiredSkills: ["Creativity", "Communication", "Adaptability"],
  },
];

export const upcomingInterviews = [
  { id: "interview-1", candidate: "Maya Brooks", role: "Community Engagement Internship", date: "August 6, 2026", time: "10:00 AM" },
  { id: "interview-2", candidate: "Jordan Williams", role: "Operations Internship", date: "August 7, 2026", time: "1:30 PM" },
  { id: "interview-3", candidate: "Avery Thompson", role: "Operations Internship", date: "August 8, 2026", time: "9:00 AM" },
];

export const employerActivity = [
  { id: "activity-1", title: "Riley Carter moved to Offer", detail: "Operations Internship", time: "2 hours ago" },
  { id: "activity-2", title: "New candidate recommended", detail: "Avery Thompson", time: "Yesterday" },
  { id: "activity-3", title: "Interview scheduled", detail: "Maya Brooks", time: "Yesterday" },
];

export const pipelineStages = [
  { label: "Recommended", value: 12 },
  { label: "Reviewing", value: 8 },
  { label: "Interview", value: 5 },
  { label: "Offer", value: 2 },
  { label: "Placed", value: 4 },
];

export const skillsDemand = [
  { skill: "Communication", score: 92 },
  { skill: "Professionalism", score: 88 },
  { skill: "Teamwork", score: 84 },
  { skill: "Problem Solving", score: 79 },
  { skill: "Leadership", score: 73 },
  { skill: "Adaptability", score: 76 },
];
